name: autobox
description: "App for record video for boxing and unboxing"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  camera: ^0.10.5
  google_mlkit_barcode_scanning: ^0.11.0
  path_provider: ^2.1.1
  intl: ^0.20.2
  permission_handler: ^11.0.1
  video_player: ^2.10.1
  chewie: ^1.13.0
  shared_preferences: ^2.5.4
  gal: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
